Tugas_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import myprofile.urls as myprofile
from myprofile.views import index as my_profile
import add_friend.urls as add_friend
import update_status.urls as update_status
import stats.urls as stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^myprofile/', include(myprofile,namespace='myprofile')),
    url(r'^friends/', include(add_friend, namespace='friends')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^dashboard/', include(stats, namespace='dashboard')),
    url(r'^$', RedirectView.as_view(url="/update-status/", permanent="True"), name='index'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
 ]

myprofile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
	]

stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

update_status/urls.py
from django.conf.urls import url
from .views import index, update_status_todo, remove_todo
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^update_status_todo', update_status_todo, name='update_status_todo'),
	url(r'^remove_todo', remove_todo, name='remove_todo'),
]

add_friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length=30)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)
	

myprofile/models.py
from django.db import models

# Create your models here.
class Biodata(models.Model):
	name = models.CharField(max_length = 100)
	birthday = models.DateField(max_length = 100)
	gender = models.CharField(max_length = 100)
	expertise = models.CharField(max_length = 100)
	description = models.TextField(max_length = 100)
	email = models.EmailField(max_length = 100)
	

stats/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models
from django.utils import timezone

class Todo(models.Model):
    fill = models.CharField(max_length=1000)
    created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
	error_messages = {
		'required': 'Input ini harus diisi',
		'invalid': 'Isi input dengan url',
	}
	attrs = {
		'class': 'form-control',
	}
	name_attrs = {
		'type': 'text',
        'class': 'form-control',
        'placeholder':'Enter your friend\'s name'
	}
	url_attrs = {
		'type': 'text',
        'class': 'form-control',
        'placeholder':'Enter your friend\'s url'
	}
	
	name = forms.CharField(label='Name', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs), error_messages=error_messages)
	url = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=url_attrs), error_messages=error_messages)

myprofile/forms.py
from django import forms

update_status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    fill_attrs = {
        'type': 'text',
        'cols': 151,
        'rows': 3,
        'class': 'todo-form-textarea',
        'placeholder':'Apa Aktivitas Anda Saat Ini?'
    }

    fill = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=fill_attrs))

add_friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django import forms
from .forms import Add_Friend_Form
from .models import Friend

# Create your views here.
response = {}
html = 'add_friend.html'

def index(request):
	friend = Friend.objects.all()
	response['author'] = 'Kelompok 3 PPW-E'
	response['friend'] = friend
	response['friend_form'] = Add_Friend_Form
	return render(request, html, response)
	
def add_friend(request):
	form = Add_Friend_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		friend = Friend(name = request.POST['name'], url = request.POST['url'])
		friend.save()
	return HttpResponseRedirect('/friends/')

myprofile/views.py
from django.shortcuts import render
from .models import Biodata


# Create your views here.
response = {}
def index(request):
	biodata = Biodata.objects.get(pk=1)
	response['biodata'] = biodata
	html = 'my_profile.html'
	return render(request, html, response)
	
		

stats/views.py
from django.shortcuts import render
from add_friend.models import Friend
from update_status.models import Todo
# Create your views here.

def index(request):
	friend = Friend.objects.count()
	feed = Todo.objects.count()
	lastFeed = Todo.objects.last()
	#lastFeed = Todo.objects.all()[Todo.objects.count()-1]
	response = {'author' : 'Hepzibah Smith', 'friend' : friend, 'feed' : feed, 'lastfeed' : lastFeed}
	return render(request, 'stats.html', response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Kelompok 3 Kelas E" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    html = 'status.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def update_status_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['fill'] = request.POST['fill']
        todo = Todo(fill=response['fill'])
        todo.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')
		
def remove_todo(request):
    try:
        idObjek = request.POST['flag']
        Todo.objects.filter(id=idObjek).delete()
    except ValueError or KeyError:
        pass
    return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Friends{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
{% endblock %}

{% block content %}
<section name="form" id="input-list">	
	<h2 class="my-list-title">Add Friend</h2>
	<div class="container">
		<form id="form" method="POST" action="{% url 'friends:add_friend' %}">
			{% csrf_token %}
			{% for field in friend_form %}
				<div class="form-group row">
					<label class="col-2 col-form-label" for="{{ field.name }}">{{ field.label }}</label>
					<div class="col-10">{{ field }}</div>
				</div>
			{% endfor %}
			<br>
			<div align="center" id="add_friend">
				<button type="submit" class="btn btn-info btn-block">Add Friend</button>
			</div>
		</form>
	</div>
</section>
<br>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">Friend List</h2>
        <div class="flex">
            {% if friend %}
                {% for data in friend %}
                    <div class="flex-item">
                        <div class="to-do-list">
							<div class="to-do-list-picture">
								<img class="rounded-circle" src="{% static 'img/blank-profile-picture-973461_960_720.png' %}" 
									width="200" height="200"/>
							</div>
                            <div class="to-do-list-title">
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added">
								Added on {{ data.created_date.date }} {{ data.created_date.time }}
                            </div>
                            <div class="to-do-list-description">
                                <a href="{{data.url}}">{{data.url}}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data teman.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

myprofile/templates/my_profile.html
{% extends "layout/base.html" %}
{% block content %}
<html lang="en">
    <meta charset="UTF-8">
    <title>{{ biodata.name }}</title>
	<h1>Profile</h1>
<h2 style="text-align: center">
	<div>
		<img class="img-circle" src="https://i.imgur.com/TF1NdQL.png"; border="0" style="float:center;width:260px;height:260px:border-radius:50%;margin-top:30px;"/>
		<p>{{ biodata.name }}</p>
	</div>
</h2>
	<table align="center" style="text-align:left">
		<tr>
			<td>Birthday	: {{ biodata.birthday }}</td>
		</tr>
		<tr>
			<td>Gender		: {{ biodata.gender }}</td>
		</tr>
		<tr>
			<td>Expertise	: {{ biodata.expertise }}</td>
		</tr>
		<tr>
			<td>Description	: {{ biodata.description }}</td>
		</tr>
		<tr>
			<td>Email		: {{ biodata.email }}</td>
		</tr>
	</table>
</html>
{% endblock %}

myprofile/templates/my_profile/partials/footer.html
<p>&copy; {{author}}</p>

stats/templates/stats.html
{% extends "layout/base.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <style>
        #aaa{
            margin-top: 7px;
            font-size: 30px;
            font-family: Arial, sans-serif;
            color: black;
        }
        #texts{
            margin-top: 10px;
            font-family: Arial, sans-serif;
            color: black;
        }
        #texts2{
            font-size: 20px;
            font-family: Arial, sans-serif;
            color: black;
        }
        #texts3{
            font-size: 20px;
            font-family: Arial, sans-serif;
            color: black;
        }
        #texts4{
            font-size: 20px;
            font-family: Arial, sans-serif;
            color: black;
        }
        #texts5{
            font-size: 20px;
            font-family: Arial, sans-serif;
            color: black;
        }
        #footer{
            font-family: Arial, sans-serif;
            color: black;
        }
        .post-fill-list{
            font-family: Arial, sans-serif;
            color: black;
        }
    </style>
    <body>
        <h2 id="aaa">Statistic</h2>
        <hr/>
        <div id="container1" style="white-space:nowrap">
            <div id="image" style="display:inline;border-radius:50%">
                <img class="img-circle" src="https://i.imgur.com/TF1NdQL.png" width=100px height=100px/>
            </div>
            <div id="texts" style="display:inline; white-space:nowrap;">
                <font size ="8">
                <b>{{author}}</b>
                </font>
            </div>
        </div>​
        <p>
            <h3 id="texts2"><strong>Change Theme</strong></h3>
            <button type="button" onclick="myFunction1()">Theme 1
            </button> 
            <button type="button2" onclick="myFunction2()">Theme 2</button>
            <h3 id="texts3"><strong>Friends</strong>     : {{friend}} People</h3>
            <h3 id="texts4"><strong>Feed</strong>       : {{feed}} Post</h3>
            <h3 id="texts5"><strong>Latest Post</strong> </h3>
            <section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if lastfeed %}
                    <div class="flex-item">
                        <div id = "bgPost"class="post-list" style="border: solid 1px #29447E; background-color:#FFF8DC; padding: 15px; margin: 0; text-align: justify">
							<br>
							<div id="container2" style="white-space:nowrap">
								<div id="image" style="display:inline;">
									<img src="https://i.imgur.com/TF1NdQL.png" width=30 height=30/>
								</div>
								<div id="texts" style="display:inline; white-space:nowrap;">
									<font size ="4">
									<b>{{author}}</b>
									</font>
								</div>
							</div>​
                            <div class="post-fill-list">
								<font size = "3">
                                {{lastfeed.fill}}
								</font>
                            </div>
							<div id = "container" style="white-space:nowrap">
								<div class="post-list-date-added" style="display:inline;">
									<font color = "gray" size = "2">
									{{lastfeed.created_date}}
									</font>
								</div>
							</div>
							<br>
						</div>
                    </div>
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section>
        </p>   
        <script>function myFunction1(){
                document.getElementById("aaa").style.color="white";
                document.getElementById("aaa").style.fontFamily="Georgia,serif";
                document.getElementById("texts").style.fontFamily="Georgia,serif";
                document.getElementById("texts2").style.fontFamily="Georgia,serif";
                document.getElementById("texts3").style.fontFamily="Georgia,serif";
                document.getElementById("texts4").style.fontFamily="Georgia,serif";
                document.getElementById("texts5").style.fontFamily="Georgia,serif";
                document.getElementById("footer").style.fontFamily="Georgia,serif";
                document.getElementById("texts").style.color="white";
                document.getElementById("texts2").style.color="white";
                document.getElementById("texts3").style.color="white";
                document.getElementById("texts4").style.color="white";
                document.getElementById("texts5").style.color="white";
                document.getElementById("footer").style.color="white";
                document.getElementById("bbb").style.backgroundColor="black";
                document.getElementById("bgPost").style.backgroundColor="white"
                
        }
            </script>
            <script>function myFunction2(){
                document.getElementById("aaa").style.color="black";
                document.getElementById("aaa").style.fontFamily="Arial,serif";
                document.getElementById("texts").style.fontFamily="Arial,serif";
                document.getElementById("texts2").style.fontFamily="Arial,serif";
                document.getElementById("texts3").style.fontFamily="Arial,serif";
                document.getElementById("texts4").style.fontFamily="Arial,serif";
                document.getElementById("texts5").style.fontFamily="Arial,serif";
                document.getElementById("footer").style.fontFamily="Arial,serif";
                document.getElementById("texts").style.color="black";
                document.getElementById("texts2").style.color="black";
                document.getElementById("texts3").style.color="black";
                document.getElementById("texts4").style.color="black";
                document.getElementById("texts5").style.color="black";
                document.getElementById("footer").style.color="black";
                document.getElementById("bbb").style.backgroundColor="beige"
                document.getElementById("bgPost").style.backgroundColor="#FFF8DC"
            }
            </script>        
    </body>
    </html>
    {% endblock %}

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="TUGAS 1">
    <meta name="author" content="{{author}}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    {% block style %}
        <!-- insert static/css here-->      
	{% endblock %}
    <title> 
        {% block title %}
			<!-- ling in-->
		{% endblock %}
    </title>
</head>

<body id="bbb" style="background-color:beige">
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

templates/partials/footer.html
<p id="footer">&copy; Kelompok 3 PPW-E</p>

templates/partials/header.html
<!-- templates/partials/header.html -->
<div class="container-fullwidth">
	<nav class="navbar navbar-default navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="#">PeweTalk</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
		  <li class="nav-item">
		<a class="nav-link" href="/update-status/">Status</a>
		</li>
		<li class="nav-item" >
		<a class="nav-link" href="/myprofile/">Profile</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="/friends/">Friends</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="/dashboard/">Dashboard</a>
		</li>
		</ul>
	</div>
	</nav>
</div>

update_status/templates/layout/status_base.html
{% extends 'layout/base.html' %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
	<link href="/static/css/bootstrap-3.3.7.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="/static/css/status.css" />


    <title>
        {% block title %} Timeline {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

update_status/templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>&copy; Made with Love by {{author}}</p>

update_status/templates/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class = "navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'lab-5:index' %}#input-list">Input Todo</a></li>
        <li><a href="{% url 'lab-5:index' %}#my-list">My List</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

update_status/templates/status.html
{% extends "layout/status_base.html" %}

{% block content %}
<h1 class="main-title">Update Status</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:update_status_todo' %}">
			<font size = "3">
            {% csrf_token %}
            {{ todo_form }}
			</font>
			<p align="right">
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Post"></p>
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">Status List</h2>
        <div class="flex">
            {% if todo %}
                {% for data in todo reversed %}
                    <div class="flex-item">
                        <div class="post-list" style="border: solid 1px #29447E; background:#FFF8DC; padding: 15px; margin: 0; text-align: justify">
							<br>
							<div id="container" style="white-space:nowrap">
								<div id="image" style="display:inline;">
									<img src="https://www.artmajeur.com/medias/standard/s/p/spuggy/artwork/1661409_meryl_streep.jpg" width=30 height=30/>
								</div>
								<div id="texts" style="display:inline; white-space:nowrap;">
									<font size ="4">
									<b>Hepzibah Smith </b>
									</font>
								</div>
							</div>​
                            <div class="post-fill-list">
								<font size = "3">
                                {{data.fill}}
								</font>
                            </div>
							<div id = "container" style="white-space:nowrap">
								<div class="post-list-date-added" style="display:inline;">
									<font color = "gray" size = "2">
									{{data.created_date}}
									</font>
								</div>
								<form id="form-{{data.id}}" method="post" action="{% url 'update-status:remove_todo' %}" style="display:inline; white-space:nowrap;">
								{% csrf_token %}
								<input type="hidden" name="flag" value="{{data.id}}" />
								<input id = "submit{{data.id}}" id="delete-{{data.id}}" type="submit" data-id="{{data.id}}" value="Delete" class="to-do-list-delete">
								</form>
							</div>
							<br>
						</div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}